### ISSUE TITLE
Does aconfig support short and long versions of fields?

### ISSUE THREAD

**Issue by ADRFranklin** [cristalhq/aconfig#94]
I'm trying to find out if it's possible that aconfig is able to parse a field that has 2 different uses, a short version (string) and a long version (struct) which provides more detailed version of the overall use.

For example
```
  dependencies:
    - name: example-plugin
      url: github://someuser/somerepo
      branch: master
      release: v1.0.0

    - name: plugin-repo-without-package-file
      url: gitlab://someuser/somerepo
      branch: dev
      release:
        name: my_plugin_{{.OS}}
        tag: v2.1.3
        type: archive
        path: plugin/plugin
```

Would I be able to do this, where I can parse it as an interface and then handle extracting it based on it's type?
